'use client'

import LegalPageTemplate from '@/components/LegalPageTemplate'

export default function LegalPage() {
  return (
    <LegalPageTemplate
      tag="Legal"
      title="Legal"
      titleEm="Disclaimer"
      date="March 2026"
      sections={[
        { title: '1. General Disclaimer', content: 'The information provided on this website and by Boost with Launchpad ("Company," "we," "us") is for general informational purposes only. While we strive to keep information accurate and current, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the website or the information, products, services, or related graphics contained on the website for any purpose.' },
        { title: '2. No Guaranteed Results', content: 'Case studies, testimonials, and performance metrics presented on this website reflect results achieved for specific clients under specific circumstances. Past performance does not guarantee future results. Individual outcomes vary based on factors including industry, market conditions, existing infrastructure, and the scope of engagement. All statistics labeled "up to" or with similar qualifiers represent best-case or upper-range outcomes observed across our client base.' },
        { title: '3. Professional Advice', content: 'Nothing on this website constitutes professional legal, financial, medical, or business advice. The content provided is intended to offer general guidance about marketing, automation, and business operations. You should consult with qualified professionals before making decisions based on information found on this website.' },
        { title: '4. Third-Party Links & Services', content: 'This website may contain links to external sites and integrates with third-party services including but not limited to Stripe, Calendly, Google, Meta, DocuSign, and Twilio. We do not control and are not responsible for the content, privacy policies, or practices of any third-party sites or services.' },
        { title: '5. Illustrative Content', content: 'Certain elements on this website, including dashboard previews, data visualizations, and interactive demonstrations, are illustrative in nature and do not represent live data or real-time system output unless explicitly labeled otherwise.' },
        { title: '6. ROI Estimates & Projections', content: 'Any ROI calculations, revenue projections, or performance estimates generated by tools on this website are based on industry averages and data from existing client engagements. These figures are estimates only and should not be relied upon as guarantees of future performance.' },
        { title: '7. Contractor Relationships', content: 'All team members associated with Boost with Launchpad operate as independent contractors. No individual is represented as an employee, officer, or executive of the Company. References to "our team" or "account teams" describe the contractor professionals engaged to deliver services on behalf of the Company.' },
        { title: '8. Limitation of Liability', content: 'To the fullest extent permitted by applicable law, the Company shall not be liable for any loss or damage, whether direct, indirect, incidental, consequential, or otherwise, arising from your use of this website or reliance on any information provided herein.' },
        { title: '9. Governing Law', content: 'This Legal Disclaimer is governed by the laws of the State of Florida. Any disputes arising from or relating to this disclaimer or your use of this website shall be resolved through binding arbitration in Palm Beach County, Florida.' },
        { title: '10. Contact', content: 'For questions about this Legal Disclaimer, contact us at hello@boostwithlaunchpad.com or through our contact page.' },
      ]}
    />
  )
}
